baseURL = "https://test-blog.aerie.jp"
languageCode = "ja-JP"
title = "Test Blog"
theme = "github-style"
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
hasCJKLanguage = true
googleAnalytics = "G-XQBJVEQBMP"

[params]
  author = "aetos"
  github = "aetos382"
  twitter = "aetos382"
  rss = true
  lastmod = true
  location = "Saitama-shi, Saitama-ken, Japan"
